#!/bin/sh

usage="Usage: $(basename "$0") [-h] <Boot directory>\n
Generate syslinux.cfg by parsing the boot loader entry configs deployed by ostree and install it into the boot directory\n
\n
where:\n
\t-h  show this help text"

case $1 in
  "") echo -e $usage; exit 1;;
  "-h") echo -e $usage; exit 0;;
  *)
esac

BOOT_DIR=$1

BOOT_SYSLINUX_DIR=${BOOT_DIR}/syslinux
SYSLINUX_CFG=${BOOT_SYSLINUX_DIR}/syslinux.cfg
mkdir -p ${BOOT_SYSLINUX_DIR}
cat << EOF > ${SYSLINUX_CFG}
UI menu.c32
PROMPT 0
MENU TITLE Alpine/Linux Boot Menu
MENU AUTOBOOT Alpine will be booted automatically in # seconds
TIMEOUT 10

EOF
cat $(ls -r ${BOOT_DIR}/loader/entries/ostree-*.conf) \
	| sed -e '/^aboot.*/d' \
	| sed -e '/^version .*/d' \
	| sed -e 's/^title/LABEL/g' \
	| sed -e 's/^linux/\tKERNEL/g' \
	| sed -e 's/^options/\tAPPEND/g' \
	| sed -e 's/^initrd/\tINITRD/g' >> ${SYSLINUX_CFG}
